import { Box, Button, Center } from '@chakra-ui/react';
import Head from 'next/head';
import { useCallback, useRef, useState } from 'react';
import ReactTags, { Tag } from 'react-tag-autocomplete';
import { ComboboxStyles } from './Combobox.styled';

type CustomTag = Tag & { value: string; type: 'email' | 'user' };

export default function Home() {
  const [tags, setTags] = useState<CustomTag[]>([]);

  const [suggestions, setSuggestions] = useState<CustomTag[]>([
    {
      id: 1,
      name: 'maciej@gmail.com',
      value: 'maciej@gmail.com',
      type: 'email',
    },
    { id: 2, name: 'Karolina', value: 'karolina@gmail.com', type: 'user' },
  ]);

  const reactTags = useRef();

  const onDelete = useCallback(
    tagIndex => {
      setTags(tags.filter((_, i) => i !== tagIndex));
    },
    [tags],
  );

  const onAddition = useCallback(
    newTag => {
      setTags([...tags, newTag]);
    },
    [tags],
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center w={'100vw'} h={'100vh'} flexDirection="column">
          <Button mb={10}>Invite teammates</Button>
          <Box width={'400px'}>
            <ComboboxStyles>
              <ReactTags
                ref={reactTags}
                tags={tags}
                placeholderText="Search names or emails..."
                suggestions={suggestions}
                onDelete={onDelete}
                onAddition={onAddition}
                suggestionComponent={({ item, query }) => {
                  return (
                    <span
                      id={`$${item.id}`}
                      className={item.name === query ? 'match' : 'no-match'}
                    >
                      {item.type}
                      {` - `}
                      {item.name}
                    </span>
                  );
                }}
              />
            </ComboboxStyles>
          </Box>
        </Center>
      </main>
    </div>
  );
}
