import { Button, Center, useDisclosure } from '@chakra-ui/react';
import Head from 'next/head';

import { Invite } from '../components/invite/invite';

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center w={'100vw'} h={'100vh'} flexDirection="column">
          <Button onClick={onOpen} variant="secondary" size="medium">
            Invite teammates
          </Button>
        </Center>
      </main>

      <Invite isOpen={isOpen} onClose={onClose} />
    </div>
  );
}
